version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: paygator-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: paygator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - paygator-network

  # Opcional: pgAdmin para gerenciar o banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: paygator-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@paygator.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - paygator-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  paygator-network:
    driver: bridge 